### ISSUE TITLE
Basic Response on Error

### ISSUE THREAD

**Issue by TheDuckGoesQuark** [rtw43/cs3099jh#2]
Suggestion for adding another field to error response JSON which contains an error message that can be shown directly to the end user. Might save the FE some hassle. 
i.e.
```
{
    "status": "error",
    "error": string,
    "message": string,
    "dev_message": string,
    "error_data": optional(anything)
}
```

**Comment by rtw43** [comment]
Sounds good,

Have a look at 76a9f5c2f5f7ef2d572fe238f7d83e06356370d7

I've added the property under the name "user_message" (rather than "message") and kept "error_description" rather than "dev_message" to maintain backwards compatibility with the previous versions of the spec.

Does this seem alright?
