### ISSUE TITLE
Error Responses

### ISSUE THREAD

**Issue by TheDuckGoesQuark** [rtw43/cs3099jh#3]
Half-question half issue.

The status field in error and success responses is either the text "error" or "success".
Would this not be the place to have the actual error code? i.e. 404, 500 etc

**Comment by rtw43** [comment]
I'm not 100% convinced by this - to me this seems like a weird inter-dependency/duplication between the transport protocol and the response content. Esp since the "error" field already gives **more** information than you get from the status code I don't really see what the advantage is.

The change you are suggesting would break compatibility (which is not a **big** issue at this stage) but I'm currently not convinced that it's justified.

Feel free to argue the case for it though.

**Comment by rtw43** [comment]
I'm going to close this for now. If anyone feels strongly enough that the change would be justified feel free to reopen.
