### ISSUE TITLE
OAuth and Logging out

### ISSUE THREAD

**Issue by TheDuckGoesQuark** [rtw43/cs3099jh#7]
Missing logout feature from tokens.

**Comment by rtw43** [comment]
"Logout" doesn't really make sense with token based authentication. If a client wishes to make a call that is unauthenticated it simply does not send the authorisation header. If a client is permanently done with an authenticated session it simply discards the token (and due to token expire the client only needs to protect against short term leaks).

The server has no notion of "state" with regard to authentication - so logout isn't really something that makes sense when not doing session based authentication. The only similar concept might be to prematurely invalidate an authentication token - note that this is only needed when:
- the client has accidentally leaked the refresh token to an adversary (the authentication token does not suffice)
- **and** the adversary is continually refreshing the token
- **and** began doing so before the token first expired.

In any other case the token will simply expire. Such invalidation would by no means be part of the normal authentication flow.

Right now I don't think this worth requiring (at least in the basic spec) since it covers such an extreme edge case and is server logic to compensate for a misbehaving client. Ability to invalidate all current sessions for a given client is certainly a good idea though - and if a backed server wants to expose this I would recommend that they expose this option through a per-user property, something like:

```javascript
{
    "id": "invalidate_tokens",
    "display": {
        "category": "security",
        "group": "Active sessions",
        "display_name": "logout all active sessions",
        "description": "Invalidate all active sessions that are logged in under this account"
    },
    "read_only": False,
    "type": "boolean",
    "value": False
}
```

**Comment by rtw43** [comment]
Gonna close this unless there is strong feeling to have a dedicated invalidate token call?
